spring:
  application:
    name: carrier-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: carrier
    open-in-view: false
  flyway:
    enabled: true
    default-schema: carrier
    schemas: carrier
    locations: classpath:db/migration
    baseline-on-migrate: true
  graphql:
    graphiql:
      enabled: true
    path: /graphql
    schema:
      locations: classpath:graphql/

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/shipment_planner?currentSchema=carrier
    username: carrier_svc
    password: carrier_pass
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/shipment_planner?currentSchema=carrier
    username: carrier_svc
    password: carrier_pass
    driver-class-name: org.postgresql.Driver
